---
- name: install ad
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: result

- name: reboot windows
  win_reboot:
    msg: "Installing AD. Rebooting..."
    reboot_timeout: 3600
    post_reboot_delay: 60

- name: install domain
  win_domain:
    dns_domain_name: "{{ dns_name }}"
    safe_mode_password: "{{ safe_mode_password }}"
