---
- hosts: "{{ hosts }}"
  tasks:
    - name: create dir C:\Temp\prueba_when
      win_file: 
        path: C:\Temp\prueba_when
        state: directory
      when: ansible_ip_addresses[0] == "192.168.17.201"
