---
- hosts: "{{ hosts }}"
  handlers:
    - name: restart apache
      win_service:
        name: Apache2.2 
        state: restarted 
      listen: "restart web"
  tasks:
    - name: Set ServerAdmin email adress 
      win_lineinfile:
        path: C:\Program Files (x86)\Apache Software Foundation\Apache2.2\conf\httpd.conf
        regex: '^ServerAdmin'
        line: 'ServerAdmin prueba@windows.com'
      notify: "restart web"