---
- hosts: "{{ hosts }}"
  tasks:
    - name: create users
      win_user:
        name: "{{ item }}"
        description: "usuario creado por ansible"
        state: present
      with_items:
        - rlujan
        - dbolivar
        - aitolive
    - name: copy files
      win_copy:
        src: "/var/tmp/{{ item }}"
        dest: C:\Temp\
        remote_src: no
      with_items:
        - file1.txt
        - file2.txt
        - file3.txt
    - name: creamos usuarios
      debug:
        msg: "usuario {{ item.user }} y con grupo {{ item.group }}"
      with_items:
        - { user: 'rlujan', group: 'unix' }
        - { user: 'dbolivar', group: 'db' }
