---
- hosts: "{{ hosts }}"
  tasks:
    - name: get files
      block:
        - win_uri:
          url: "http://{{ hosts }}"
      rescue:
        - debug:
            msg: "Debes levantar apache"
      always:
        - debug:
            msg: "Siempre ejecuto esto"
       
