---
- hosts: "{{ hosts }}"
  tasks:
    - name: analizamos variable empleado
      debug:
        msg: 
          - "nombre: {{ empleado.nombre }}"
          - "wiw: {{ empleado.wiw }}"
          - "grupo: {{ empleado.grupo }}"

    - name: analizamos 2 variable empleado
      debug:
        msg: 
          - "nombre: {{ empleado['nombre'] }}"
          - "wiw: {{ empleado['nombre'] }}"
          - "grupo: {{ empleado['grupo'] }}"
      
    - name: analizamos variable empleado2
      debug:
        msg: 
          - "nombre: {{ empleado2[1].nombre }}"
          - "wiw: {{ empleado2[1].wiw }}"
          - "grupo: {{ empleado2[1].grupo }}"

    - name: analizamos2 variable empleado2
      debug:
        msg: 
          - "nombre: {{ item.nombre }}"
          - "wiw: {{ item.wiw }}"
          - "grupo: {{ item.grupo }}"
      with_items:
        - "{{ empleado2 }}"