---
- hosts: "{{ hosts }}"
  tasks:
   - name: "{{ accion }} servicio {{ servicio }}"
     win_service:
      name: "{{ servicio }}"
      state: "{{ accion }}"
     when: servicio is defined and accion is defined
