---
- hosts: "{{ hosts }}"
  tasks:
   - name: Crear fichero {{ filename }} con contenido
     win_copy:
       dest: "C:\\Temp\\{{ filename }}"
       content: "{{ contenido }}"
     when: content is defined
   - name: Nos aseguramos que el grupo {{ filegroup }} existe
     win_group:
       name: "{{ filegroup }}"
       description: Lab Group
       state: present
   - name: Nos aseguramos que el usuario {{ fileowner }} existe
     win_user:
       name: "{{ fileowner }}"
       state: present
       groups:
         - "{{ filegroup }}"
   - name: Seteamos permisos {{ filegroup }} a fichero
     win_owner:
       path: "C:\\Temp\\{{ filename }}"
       user: "{{ fileowner }}"
