---
- hosts: "{{ hosts }}"
  tasks:
   - name: Stop service Print Spooler
     win_service:
      name: spooler
      state: stopped
      #start_mode: disabled

      #Comandos en powershell para validar 
      #Get-Service Spooler
      #Start-Service Spooler
      #Stop-Service Spooler